"""initial schema

Revision ID: e8de20c22fae
Revises:
Create Date: 2026-09-04 05:17:43.262719
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e8de20c22fae"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "tokens", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("hits", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_llm_cache")),
    )
    op.create_table(
        "orgs",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("retention_days", sa.Integer(), server_default="90", nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orgs")),
        sa.UniqueConstraint("slug", name=op.f("uq_orgs_slug")),
    )
    op.create_index(op.f("ix_orgs_created_at"), "orgs", ["created_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("member_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_score", sa.SmallInteger(), nullable=True),
        sa.Column("distinct_domains", sa.Integer(), server_default="0", nullable=False),
        sa.Column("distinct_prefixes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("distinct_asns", sa.Integer(), server_default="0", nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "member_count >= 0", name=op.f("ck_campaigns_member_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_campaigns_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("org_id", "name", name="uq_campaigns_org_id_name"),
    )
    op.create_index(op.f("ix_campaigns_created_at"), "campaigns", ["created_at"], unique=False)
    op.create_index(op.f("ix_campaigns_org_id"), "campaigns", ["org_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("case_ref", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "analysing",
                "enriching",
                "complete",
                "failed",
                name="casestatus",
                native_enum=False,
                length=40,
            ),
            server_default="received",
            nullable=False,
        ),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column(
            "band",
            sa.Enum(
                "benign",
                "suspicious",
                "likely_malicious",
                "high",
                "critical",
                name="band",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "benign",
                "phishing",
                "spear_phishing",
                "bec",
                "credential_phishing",
                "impersonation",
                "malware_delivery",
                "extortion",
                "unknown",
                name="classification",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("data_completeness", sa.SmallInteger(), nullable=True),
        sa.Column("weights_version", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_completeness IS NULL OR (data_completeness >= 0 AND data_completeness <= 8)",
            name=op.f("ck_cases_completeness_range"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)", name=op.f("ck_cases_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_cases_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_cases_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("org_id", "case_ref", name="uq_cases_org_id_case_ref"),
    )
    op.create_index(op.f("ix_cases_created_at"), "cases", ["created_at"], unique=False)
    op.create_index("ix_cases_org_created", "cases", ["org_id", "created_at"], unique=False)
    op.create_index(op.f("ix_cases_org_id"), "cases", ["org_id"], unique=False)
    op.create_index("ix_cases_org_score", "cases", ["org_id", "score"], unique=False)
    op.create_table(
        "graph_nodes",
        sa.Column(
            "type",
            sa.Enum(
                "email",
                "sender_address",
                "reply_to_address",
                "display_name",
                "domain",
                "host",
                "url",
                "ip",
                "net_prefix",
                "asn",
                "attachment_hash",
                "dkim_identity",
                "tool_fingerprint",
                "campaign",
                name="nodetype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=True),
        sa.Column("idf", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("is_hub", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_graph_nodes_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_nodes")),
        sa.UniqueConstraint("org_id", "type", "value", name="uq_graph_nodes_org_type_value"),
    )
    op.create_index(op.f("ix_graph_nodes_org_id"), "graph_nodes", ["org_id"], unique=False)
    op.create_index("ix_graph_nodes_org_type", "graph_nodes", ["org_id", "type"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner", "analyst", "viewer", name="membershiprole", native_enum=False, length=40
            ),
            server_default="analyst",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\"role\" IN ('owner', 'analyst', 'viewer')", name=op.f("ck_memberships_role_vocab")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_memberships_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "user_id", name=op.f("pk_memberships")),
    )
    op.create_table(
        "ai_analysis",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column(
            "call_kind",
            sa.Enum("extract", "narrative", name="aicallkind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("output_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("quotes_validated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quotes_dropped", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "prompt_injection_detected", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "tokens", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("cached", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_ai_analysis_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_ai_analysis_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analysis")),
    )
    op.create_index(
        "ix_ai_analysis_case_kind", "ai_analysis", ["case_id", "call_kind"], unique=False
    )
    op.create_index(op.f("ix_ai_analysis_created_at"), "ai_analysis", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_ai_analysis_input_sha256"), "ai_analysis", ["input_sha256"], unique=False
    )
    op.create_index(op.f("ix_ai_analysis_org_id"), "ai_analysis", ["org_id"], unique=False)
    op.create_table(
        "auth_results",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column(
            "mechanism",
            sa.Enum(
                "spf", "dkim", "dmarc", "arc", name="authmechanism", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column(
            "result_reported",
            sa.Enum(
                "pass",
                "fail",
                "softfail",
                "neutral",
                "none",
                "temperror",
                "permerror",
                "indeterminate",
                name="auth_result_reported",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "result_recomputed",
            sa.Enum(
                "pass",
                "fail",
                "softfail",
                "neutral",
                "none",
                "temperror",
                "permerror",
                "indeterminate",
                name="auth_result_recomputed",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("authserv_id", sa.String(length=256), nullable=True),
        sa.Column("trusted_source", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("aligned", sa.Boolean(), nullable=True),
        sa.Column("selector", sa.String(length=128), nullable=True),
        sa.Column("d_domain", sa.String(length=253), nullable=True),
        sa.Column("h_tags", sa.Text(), nullable=True),
        sa.Column("l_tag", sa.Integer(), nullable=True),
        sa.Column("policy", sa.String(length=64), nullable=True),
        sa.Column("caveat", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_auth_results_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_auth_results_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_results")),
    )
    op.create_index(
        "ix_auth_results_case_mechanism", "auth_results", ["case_id", "mechanism"], unique=False
    )
    op.create_index(op.f("ix_auth_results_org_id"), "auth_results", ["org_id"], unique=False)
    op.create_table(
        "campaign_members",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("dna_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "locus_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "shared_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dna_score >= 0 AND dna_score <= 1", name=op.f("ck_campaign_members_dna_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_members_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_campaign_members_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_campaign_members_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_members")),
        sa.UniqueConstraint("campaign_id", "case_id", name="uq_campaign_members_campaign_case"),
    )
    op.create_index(
        op.f("ix_campaign_members_case_id"), "campaign_members", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_members_created_at"), "campaign_members", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_members_org_id"), "campaign_members", ["org_id"], unique=False
    )
    op.create_table(
        "dna_fingerprints",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column(
            "locus_i", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locus_d", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locus_n", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locus_m", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locus_c", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locus_p", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("barcode", sa.String(length=256), nullable=True),
        sa.Column("dna_version", sa.String(length=16), server_default="v1", nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_dna_fingerprints_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_dna_fingerprints_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dna_fingerprints")),
        sa.UniqueConstraint("case_id", name="uq_dna_fingerprints_case_id"),
    )
    op.create_index(
        op.f("ix_dna_fingerprints_created_at"), "dna_fingerprints", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dna_fingerprints_org_id"), "dna_fingerprints", ["org_id"], unique=False
    )
    op.create_table(
        "email_artifacts",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "upload", "extension", "api", name="artifactsource", native_enum=False, length=40
            ),
            server_default="upload",
            nullable=False,
        ),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acquired_by", sa.UUID(), nullable=True),
        sa.Column(
            "parse_status",
            sa.Enum(
                "pending",
                "parsed",
                "malformed",
                "rejected",
                name="parsestatus",
                native_enum=False,
                length=40,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("content_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(sha256) = 64", name=op.f("ck_email_artifacts_sha256_length")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_email_artifacts_size_positive")),
        sa.ForeignKeyConstraint(
            ["acquired_by"],
            ["users.id"],
            name=op.f("fk_email_artifacts_acquired_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_email_artifacts_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_email_artifacts_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_artifacts")),
        sa.UniqueConstraint("org_id", "sha256", name="uq_email_artifacts_org_id_sha256"),
    )
    op.create_index(
        op.f("ix_email_artifacts_case_id"), "email_artifacts", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_artifacts_created_at"), "email_artifacts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_email_artifacts_org_id"), "email_artifacts", ["org_id"], unique=False)
    op.create_table(
        "email_headers",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("value_raw", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("above_boundary", sa.Boolean(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_email_headers_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_email_headers_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_headers")),
    )
    op.create_index(
        "ix_email_headers_case_ordinal", "email_headers", ["case_id", "ordinal"], unique=False
    )
    op.create_index(op.f("ix_email_headers_name"), "email_headers", ["name"], unique=False)
    op.create_index(op.f("ix_email_headers_org_id"), "email_headers", ["org_id"], unique=False)
    op.create_table(
        "evidence_events",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "acquired",
                "parsed",
                "auth_evaluated",
                "origin_reconstructed",
                "enriched",
                "ai_analysed",
                "scored",
                "campaign_linked",
                "analyst_note",
                "case_viewed",
                "artifact_downloaded",
                "report_generated",
                "evidence_verified",
                name="evidenceaction",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("signing_key_id", sa.String(length=64), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "\"action\" IN ('acquired', 'parsed', 'auth_evaluated', 'origin_reconstructed', 'enriched', 'ai_analysed', 'scored', 'campaign_linked', 'analyst_note', 'case_viewed', 'artifact_downloaded', 'report_generated', 'evidence_verified')",
            name=op.f("ck_evidence_events_action_vocab"),
        ),
        sa.CheckConstraint(
            "char_length(entry_hash) = 64", name=op.f("ck_evidence_events_entry_hash_length")
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_evidence_events_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_evidence_events_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_evidence_events_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_events")),
        sa.UniqueConstraint("case_id", "seq", name="uq_evidence_events_case_id_seq"),
    )
    op.create_index(
        "ix_evidence_events_case_seq", "evidence_events", ["case_id", "seq"], unique=False
    )
    op.create_index(op.f("ix_evidence_events_org_id"), "evidence_events", ["org_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column(
            "signal_group",
            sa.Enum(
                "authentication",
                "identity",
                "infrastructure",
                "url_domain",
                "content",
                "attachment",
                "threat_intel",
                "campaign",
                name="findinggroup",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "low",
                "medium",
                "high",
                "critical",
                name="severity",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("score_contribution", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("evidence_ref", sa.String(length=300), nullable=True),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("mitre_technique", sa.String(length=32), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\"signal_group\" IN ('authentication', 'identity', 'infrastructure', 'url_domain', 'content', 'attachment', 'threat_intel', 'campaign')",
            name=op.f("ck_findings_signal_group_vocab"),
        ),
        sa.CheckConstraint(
            "score_contribution >= -100 AND score_contribution <= 100",
            name=op.f("ck_findings_contribution_range"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_findings_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_findings_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index("ix_findings_case_group", "findings", ["case_id", "signal_group"], unique=False)
    op.create_index(op.f("ix_findings_created_at"), "findings", ["created_at"], unique=False)
    op.create_index(op.f("ix_findings_org_id"), "findings", ["org_id"], unique=False)
    op.create_index(op.f("ix_findings_rule_id"), "findings", ["rule_id"], unique=False)
    op.create_table(
        "graph_edges",
        sa.Column("src_id", sa.UUID(), nullable=False),
        sa.Column("dst_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "sent_from",
                "observed_at",
                "replies_to",
                "contains_url",
                "contains_attachment",
                "resolves_to",
                "hosted_on",
                "announced_by",
                "signed_by",
                "uses_tool",
                "similar_to",
                "member_of",
                name="edgetype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=6, scale=3), server_default="1.0", nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dst_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_dst_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_graph_edges_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["src_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_src_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_edges")),
        sa.UniqueConstraint("org_id", "src_id", "dst_id", "type", name="uq_graph_edges_triple"),
    )
    op.create_index("ix_graph_edges_dst", "graph_edges", ["org_id", "dst_id"], unique=False)
    op.create_index(op.f("ix_graph_edges_org_id"), "graph_edges", ["org_id"], unique=False)
    op.create_index("ix_graph_edges_src", "graph_edges", ["org_id", "src_id"], unique=False)
    op.create_table(
        "indicators",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "ip",
                "net_prefix",
                "domain",
                "host",
                "url",
                "email",
                "file_hash",
                "asn",
                "message_id",
                name="indicatortype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("normalised", sa.Text(), nullable=False),
        sa.Column("registrable_domain", sa.String(length=253), nullable=True),
        sa.Column("idf", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("is_hub", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_indicators_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_indicators_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicators")),
        sa.UniqueConstraint("case_id", "type", "normalised", name="uq_indicators_case_type_norm"),
    )
    op.create_index(op.f("ix_indicators_created_at"), "indicators", ["created_at"], unique=False)
    op.create_index(op.f("ix_indicators_org_id"), "indicators", ["org_id"], unique=False)
    op.create_index(
        "ix_indicators_org_type_norm", "indicators", ["org_id", "type", "normalised"], unique=False
    )
    op.create_index(
        op.f("ix_indicators_registrable_domain"), "indicators", ["registrable_domain"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "enrich_indicators",
                "ai_extract",
                "ai_narrative",
                "compute_dna",
                "link_campaign",
                "generate_report",
                "anchor_evidence",
                name="jobkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "done",
                "failed",
                "dead",
                name="jobstate",
                native_enum=False,
                length=40,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\"state\" IN ('queued', 'running', 'done', 'failed', 'dead')",
            name=op.f("ck_jobs_state_vocab"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_non_negative")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_jobs_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_jobs_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_case", "jobs", ["case_id"], unique=False)
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["run_after", "created_at"],
        unique=False,
        postgresql_where=sa.text("state = 'queued'"),
    )
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_jobs_org_id"), "jobs", ["org_id"], unique=False)
    op.create_index(
        "uq_jobs_active_kind_per_case",
        "jobs",
        ["case_id", "kind"],
        unique=True,
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    op.create_table(
        "origin_assessment",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("feos_ip", postgresql.INET(), nullable=True),
        sa.Column("feos_prefix", postgresql.CIDR(), nullable=True),
        sa.Column("feos_asn", sa.Integer(), nullable=True),
        sa.Column("feos_org", sa.String(length=256), nullable=True),
        sa.Column("feos_country", sa.String(length=2), nullable=True),
        sa.Column("net_type", sa.String(length=32), nullable=True),
        sa.Column("boundary_hop_seq", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "confidence_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("geo_dataset", sa.String(length=64), nullable=True),
        sa.Column("geo_version", sa.String(length=64), nullable=True),
        sa.Column("evaluated_for_date", sa.Date(), nullable=True),
        sa.Column("claim_text", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 95",
            name=op.f("ck_origin_assessment_confidence_never_certain"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_origin_assessment_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_origin_assessment_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_origin_assessment")),
        sa.UniqueConstraint("case_id", name="uq_origin_assessment_case_id"),
    )
    op.create_index(
        op.f("ix_origin_assessment_created_at"), "origin_assessment", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_origin_assessment_org_id"), "origin_assessment", ["org_id"], unique=False
    )
    op.create_table(
        "received_hops",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("helo", sa.String(length=512), nullable=True),
        sa.Column("rdns_claim", sa.String(length=512), nullable=True),
        sa.Column("observed_ip", postgresql.INET(), nullable=True),
        sa.Column("by_host", sa.String(length=512), nullable=True),
        sa.Column("protocol", sa.String(length=64), nullable=True),
        sa.Column("tls_info", sa.String(length=256), nullable=True),
        sa.Column("hop_ts_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ip_class",
            sa.Enum(
                "public",
                "private",
                "loopback",
                "link_local",
                "cgnat",
                "reserved",
                "unknown",
                name="ipclass",
                native_enum=False,
                length=40,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "org_internal",
                "trusted_provider",
                "known_forwarder",
                "external",
                name="hoprole",
                native_enum=False,
                length=40,
            ),
            server_default="external",
            nullable=False,
        ),
        sa.Column(
            "trust_state",
            sa.Enum(
                "vouched",
                "boundary",
                "asserted",
                "forged",
                name="truststate",
                native_enum=False,
                length=40,
            ),
            server_default="asserted",
            nullable=False,
        ),
        sa.Column("asn", sa.Integer(), nullable=True),
        sa.Column("asn_org", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("net_type", sa.String(length=32), nullable=True),
        sa.Column(
            "anomalies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_received_hops_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_received_hops_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_received_hops")),
        sa.UniqueConstraint("case_id", "seq", name="uq_received_hops_case_id_seq"),
    )
    op.create_index("ix_received_hops_observed_ip", "received_hops", ["observed_ip"], unique=False)
    op.create_index("ix_received_hops_org_asn", "received_hops", ["org_id", "asn"], unique=False)
    op.create_index(op.f("ix_received_hops_org_id"), "received_hops", ["org_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("redacted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "redaction_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("includes_s63_cert", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("merkle_root", sa.String(length=64), nullable=True),
        sa.Column("generated_by", sa.UUID(), nullable=True),
        sa.Column("state", sa.String(length=24), server_default="pending", nullable=False),
        sa.Column("page_count", sa.SmallInteger(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_reports_version_positive")),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_reports_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
            name=op.f("fk_reports_generated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name=op.f("fk_reports_org_id_orgs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("case_id", "version", name="uq_reports_case_id_version"),
    )
    op.create_index(op.f("ix_reports_case_id"), "reports", ["case_id"], unique=False)
    op.create_index(op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False)
    op.create_index(op.f("ix_reports_org_id"), "reports", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_org_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_index(op.f("ix_reports_case_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_received_hops_org_id"), table_name="received_hops")
    op.drop_index("ix_received_hops_org_asn", table_name="received_hops")
    op.drop_index("ix_received_hops_observed_ip", table_name="received_hops")
    op.drop_table("received_hops")
    op.drop_index(op.f("ix_origin_assessment_org_id"), table_name="origin_assessment")
    op.drop_index(op.f("ix_origin_assessment_created_at"), table_name="origin_assessment")
    op.drop_table("origin_assessment")
    op.drop_index(
        "uq_jobs_active_kind_per_case",
        table_name="jobs",
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_jobs_org_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_index(
        "ix_jobs_claimable", table_name="jobs", postgresql_where=sa.text("state = 'queued'")
    )
    op.drop_index("ix_jobs_case", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_indicators_registrable_domain"), table_name="indicators")
    op.drop_index("ix_indicators_org_type_norm", table_name="indicators")
    op.drop_index(op.f("ix_indicators_org_id"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_created_at"), table_name="indicators")
    op.drop_table("indicators")
    op.drop_index("ix_graph_edges_src", table_name="graph_edges")
    op.drop_index(op.f("ix_graph_edges_org_id"), table_name="graph_edges")
    op.drop_index("ix_graph_edges_dst", table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index(op.f("ix_findings_rule_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_org_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_created_at"), table_name="findings")
    op.drop_index("ix_findings_case_group", table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_evidence_events_org_id"), table_name="evidence_events")
    op.drop_index("ix_evidence_events_case_seq", table_name="evidence_events")
    op.drop_table("evidence_events")
    op.drop_index(op.f("ix_email_headers_org_id"), table_name="email_headers")
    op.drop_index(op.f("ix_email_headers_name"), table_name="email_headers")
    op.drop_index("ix_email_headers_case_ordinal", table_name="email_headers")
    op.drop_table("email_headers")
    op.drop_index(op.f("ix_email_artifacts_org_id"), table_name="email_artifacts")
    op.drop_index(op.f("ix_email_artifacts_created_at"), table_name="email_artifacts")
    op.drop_index(op.f("ix_email_artifacts_case_id"), table_name="email_artifacts")
    op.drop_table("email_artifacts")
    op.drop_index(op.f("ix_dna_fingerprints_org_id"), table_name="dna_fingerprints")
    op.drop_index(op.f("ix_dna_fingerprints_created_at"), table_name="dna_fingerprints")
    op.drop_table("dna_fingerprints")
    op.drop_index(op.f("ix_campaign_members_org_id"), table_name="campaign_members")
    op.drop_index(op.f("ix_campaign_members_created_at"), table_name="campaign_members")
    op.drop_index(op.f("ix_campaign_members_case_id"), table_name="campaign_members")
    op.drop_table("campaign_members")
    op.drop_index(op.f("ix_auth_results_org_id"), table_name="auth_results")
    op.drop_index("ix_auth_results_case_mechanism", table_name="auth_results")
    op.drop_table("auth_results")
    op.drop_index(op.f("ix_ai_analysis_org_id"), table_name="ai_analysis")
    op.drop_index(op.f("ix_ai_analysis_input_sha256"), table_name="ai_analysis")
    op.drop_index(op.f("ix_ai_analysis_created_at"), table_name="ai_analysis")
    op.drop_index("ix_ai_analysis_case_kind", table_name="ai_analysis")
    op.drop_table("ai_analysis")
    op.drop_table("memberships")
    op.drop_index("ix_graph_nodes_org_type", table_name="graph_nodes")
    op.drop_index(op.f("ix_graph_nodes_org_id"), table_name="graph_nodes")
    op.drop_table("graph_nodes")
    op.drop_index("ix_cases_org_score", table_name="cases")
    op.drop_index(op.f("ix_cases_org_id"), table_name="cases")
    op.drop_index("ix_cases_org_created", table_name="cases")
    op.drop_index(op.f("ix_cases_created_at"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_campaigns_org_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_created_at"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_orgs_created_at"), table_name="orgs")
    op.drop_table("orgs")
    op.drop_table("llm_cache")
    # ### end Alembic commands ###
