"""Column conventions shared by every model.

Consistency here is not cosmetic: ``org_id`` on every tenant table is what makes
a single RLS policy template correct everywhere, and uniform ``timestamptz``
columns are what make the forensic timeline reconstructable.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, func, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column


def enum_column(python_enum: type, *, name: str | None = None, **kwargs: Any) -> SAEnum:
    """Render a Python enum as a plain ``VARCHAR``.

    Three decisions are folded into this helper.

    *Not a native Postgres enum*: native enums cannot drop a value and can only
    append, turning a routine vocabulary change into a table rewrite.

    *No auto-generated CHECK constraint* (``create_constraint=False``): Alembic
    reflects such constraints from Postgres but cannot match them back to the
    SQLAlchemy Enum that produced them, so every ``alembic check`` run proposes
    dropping all of them. That turns the drift detector into permanent noise --
    and a drift detector nobody trusts is worse than a missing constraint,
    because it is where a *real* schema divergence goes unnoticed. Values are
    validated by SQLAlchemy on flush (``validate_strings``) and by Pydantic at
    the API boundary. Where database-level enforcement genuinely matters --
    authorization, audit, queue state -- an explicit, named CHECK constraint is
    declared in ``__table_args__`` via :func:`enum_check`, which does round-trip
    correctly because it has a stable name of our choosing.

    *Explicit ``name``*: the auto-derived constraint name comes from the enum
    type, so two columns of one type on one table would collide.
    """
    return SAEnum(
        python_enum,
        name=name,
        native_enum=False,
        create_constraint=False,
        validate_strings=True,
        length=40,
        values_callable=lambda e: [m.value for m in e],
        **kwargs,
    )


def enum_check(column: str, python_enum: type[Any], constraint_name: str) -> CheckConstraint:
    """An explicitly named CHECK constraint restricting ``column`` to the enum.

    Used on the tables where an out-of-vocabulary value would be a security or
    correctness problem rather than a data-quality one. Unlike the constraint
    SQLAlchemy generates from an Enum, this one has a name we control, so
    ``alembic check`` can match it and drift detection keeps working.

    ``constraint_name`` is the SHORT form: the metadata naming convention
    prepends ``ck_<table>_``. The column is quoted so a name that collides with
    a SQL keyword still produces valid DDL.
    """
    allowed = ", ".join(f"'{m.value}'" for m in python_enum)
    return CheckConstraint(f'"{column}" IN ({allowed})', name=constraint_name)


class UUIDPrimaryKey:
    """Server-generated UUID primary key.

    Generated by Postgres rather than Python so a row inserted by a migration,
    a psql session or the application is indistinguishable.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class CreatedAt:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )


class Timestamped(CreatedAt):
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class OrgScoped:
    """Tenant discriminator.

    Present on every table that holds customer data. Two independent layers
    guard it: the application always filters on ``org_id``, and Postgres RLS
    enforces the same predicate. A forgotten WHERE clause must not leak another
    organisation's correspondence.
    """

    @property
    def __org_fk__(self) -> str:  # documentation hook; not used by SQLAlchemy
        return "orgs.id"

    org_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("orgs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
